#!/bin/ksh --  # -*-perl-*-
eval 'exec $PERL $0 ${1+"$@"}'
  if 0;

use strict;
use POSIX;
use DBI();

my $year = 1900 + (localtime(time))[5];

my ($path,$cmd) = (".",$0);
if( $0 =~ /\/([^\/]+)$/ ) { ($path,$cmd) = ($`,$1); }

my $division = shift @ARGV;
die "\nUsage::$cmd division\n\n" unless defined $division;

$division =~ tr/a-z/A-Z/;
die "\nSorry:: Division must be a single letter\n\n" unless $division =~ /^[A-Z]$/;

my $dbh = DBI->connect("DBI:mysql:database=mcsl;host=localhost","mcsl","flippers");

my @x = @{$dbh->selectall_arrayref("select id,name from teams where division='$division' and year=$year")};
my %teams = map { $_->[0] => $_->[1] } @x;

my @events;
@x = @{$dbh->selectall_arrayref("select id,name,relay,divswimmers from events")};
foreach my $x (@x) 
{
  $events[$x->[0]] = { id=>$x->[0], name=>$x->[1], relay=>$x->[2], swimmers=>$x->[3] };
}

@x = @{$dbh->selectall_arrayref("select id,place,points from points where type='divisional'")};
foreach my $x (@x)
{
  $events[$x->[0]]->{points}[$x->[1]-1] = $x->[2];
}

my %stats;
foreach my $team (keys %teams)
{
  @{$stats{$team}} = load_stats($team);
}

my %score;
foreach my $i (1..$#events)
{
  my %pts = compete(\@events, \%stats, $i);
  foreach my $x (keys %pts) { $score{$x} += $pts{$x}; }
}

print "\n";

my $len;
foreach my $x (values %teams)
{
  my $lx = length($x);
  $len = $lx if $lx > $len;
}
my @teams = sort { $score{$b} <=> $score{$a} } keys %teams;
foreach my $i (0..$#teams)
{
  my $place = $i+1;
  my $name  = $teams{$teams[$i]};
  $name .= "."x($len+3-length($name));
  print "$place) $name.$score{$teams[$i]}\n";
}
print "\n";

foreach my $i (1..$#events)
{
  my $event = $events[$i];
  print "\n$event->{id}) $event->{name}\n";
  if($event->{place})
  {
    my $pos=1;
    foreach my $x (@{$event->{place}})
    {
      my $time = $x->[0];
      
      my $min = floor($time/60);
      $time -= 60*$min;
      my $sec = floor($time);
      $time -= $sec;
      my $frac = floor(100*$time+0.5);

      $frac = "0$frac" if $frac<10;
      $sec  = "0$sec" if $sec<10 && $min>0;
      $time = "$sec.$frac";
      $time = "$min:$time" if $min>0;

      my $name = ( $event->{relay} ? $teams{$x->[2]} : "$x->[1] ($x->[2])" );
      
      $name .= " "x(30-length($name));
      $pos  = " $pos" if $pos<10;
      $time = " "x(8-length($time)) . $time;
      print "  $pos.  $name    $time\n";
      $pos++;
    }
  }
}




sub load_stats
{
  my $id = shift;

  my @stats;
  my @x = @{$dbh->selectall_arrayref("select event,swimmer,min(time) from results where team='$id' and year=$year group by event,swimmer")};
  foreach my $x (@x)
  {
    $stats[$x->[0]]->{$x->[1]} = $x->[2];
  }

  @x = @{$dbh->selectall_arrayref("select event,lane,min(time) from relays where team='$id' and year=$year group by event,lane")};
  foreach my $x (@x)
  {
    $stats[$x->[0]]->{$x->[1]} = $x->[2];
  }

  my @rval;
  while(@stats)
  {
    my $x = shift @stats;
    if($x)
    {
      $x = [ sort {$a->[0] <=> $b->[0]} map { [ $x->{$_}, $_, $id ] } keys %$x ];
    }
    push @rval, $x;
  }

  return @rval;
}


sub compete
{
  my $events = shift;
  my $stats = shift;
  my $eventID = shift;
  
  my $event = $events[$eventID];
  my $n = $event->{swimmers};

  my @stats;
  foreach my $x (keys %$stats)
  {
    my $xx = $stats->{$x}[$eventID];
    if($xx)
    {
      my @x = @$xx;
      splice @x, $n;
      push @stats, @x;
    }
  }

  my %rval;
  return %rval unless @stats;

  my @place = sort { $a->[0] <=> $b->[0] } @stats;

  $event->{place} = [@place];

  my @points =  @{$event->{points}};

  while(@points && @place)
  {
    my $place = shift @place;
    my $points = shift @points;
    $rval{$place->[2]} += $points;
  }
  return %rval;
}
