DELETE FROM teams where year=2013;
INSERT INTO teams VALUES ('A','Ashton','H',2013);
INSERT INTO teams VALUES ('B','Bannockburn','G',2013);
INSERT INTO teams VALUES ('BE','Bethesda','A',2013);
INSERT INTO teams VALUES ('C','Cedarbrook','B',2013);
INSERT INTO teams VALUES ('CA','Calverton','I',2013);
INSERT INTO teams VALUES ('CB','Connecticut Belair','D',2013);
INSERT INTO teams VALUES ('CCR','Chevy Chase Rec. Assoc.','H',2013);
INSERT INTO teams VALUES ('CG','Country Glen','C',2013);
INSERT INTO teams VALUES ('CLM','Clopper''s Mill','K',2013);
INSERT INTO teams VALUES ('CS','Carderock Springs','J',2013);
INSERT INTO teams VALUES ('D','Daleview','G',2013);
INSERT INTO teams VALUES ('DA','Damascus','E',2013);
INSERT INTO teams VALUES ('DF','Diamond Farm','L',2013);
INSERT INTO teams VALUES ('DT','Darnestown','A',2013);
INSERT INTO teams VALUES ('EG','East Gate','M',2013);
INSERT INTO teams VALUES ('EW','Eldwick','K',2013);
INSERT INTO teams VALUES ('FH','Flower Hill','M',2013);
INSERT INTO teams VALUES ('FM','Fallsmead','N',2013);
INSERT INTO teams VALUES ('FO','Forest Knolls','L',2013);
INSERT INTO teams VALUES ('FR','Franklin Knolls','F',2013);
INSERT INTO teams VALUES ('FV','Flower Valley','F',2013);
INSERT INTO teams VALUES ('G','Glenwood','F',2013);
INSERT INTO teams VALUES ('GER','Germantown','D',2013);
INSERT INTO teams VALUES ('GM','Glenmont','M',2013);
INSERT INTO teams VALUES ('GP','Garrett Park','D',2013);
INSERT INTO teams VALUES ('H','Hillandale','J',2013);
INSERT INTO teams VALUES ('HA','Hallowell','C',2013);
INSERT INTO teams VALUES ('IF','Inverness Forest','G',2013);
INSERT INTO teams VALUES ('JC','James Creek','N',2013);
INSERT INTO teams VALUES ('K','Kenmont','K',2013);
INSERT INTO teams VALUES ('KFM','King Farm','E',2013);
INSERT INTO teams VALUES ('KL','Kentlands','E',2013);
INSERT INTO teams VALUES ('KM','Kemp Mill','O',2013);
INSERT INTO teams VALUES ('LB','Long Branch','J',2013);
INSERT INTO teams VALUES ('LF','Little Falls','F',2013);
INSERT INTO teams VALUES ('LLD','Lakelands','E',2013);
INSERT INTO teams VALUES ('LM','Lake Marion','I',2013);
INSERT INTO teams VALUES ('MB','Middlebridge','O',2013);
INSERT INTO teams VALUES ('MCF','Manchester Farm','D',2013);
INSERT INTO teams VALUES ('MCT','Mill Creek Towne','B',2013);
INSERT INTO teams VALUES ('MM','Merrimack Park','F',2013);
INSERT INTO teams VALUES ('MO','Mohican','E',2013);
INSERT INTO teams VALUES ('MS','Montgomery Square','L',2013);
INSERT INTO teams VALUES ('MW','Manor Woods','J',2013);
INSERT INTO teams VALUES ('NCC','North Chevy Chase','H',2013);
INSERT INTO teams VALUES ('NGV','Norbeck Grove','L',2013);
INSERT INTO teams VALUES ('NH','Norbeck Hills','L',2013);
INSERT INTO teams VALUES ('NMC','New Mark Commons','N',2013);
INSERT INTO teams VALUES ('NO','North Creek','H',2013);
INSERT INTO teams VALUES ('NWB','Northwest Branch','G',2013);
INSERT INTO teams VALUES ('O','Oakview','O',2013);
INSERT INTO teams VALUES ('OF','Old Farm','K',2013);
INSERT INTO teams VALUES ('OG','Old Georgetown','C',2013);
INSERT INTO teams VALUES ('OM','Olney Mill','I',2013);
INSERT INTO teams VALUES ('P','Parkland','O',2013);
INSERT INTO teams VALUES ('PA','Palisades','H',2013);
INSERT INTO teams VALUES ('PGL','Potomac Glen','C',2013);
INSERT INTO teams VALUES ('PL','Poolesville','K',2013);
INSERT INTO teams VALUES ('PLT','Plantations','K',2013);
INSERT INTO teams VALUES ('PO','Potomac','D',2013);
INSERT INTO teams VALUES ('PW','Potomac Woods','B',2013);
INSERT INTO teams VALUES ('QO','Quince Orchard','B',2013);
INSERT INTO teams VALUES ('QV','Quail Valley','M',2013);
INSERT INTO teams VALUES ('RC','Rock Creek','G',2013);
INSERT INTO teams VALUES ('RE','Regency Estates','H',2013);
INSERT INTO teams VALUES ('RF','River Falls','D',2013);
INSERT INTO teams VALUES ('RH','Robin Hood','F',2013);
INSERT INTO teams VALUES ('RS','Rockshire','J',2013);
INSERT INTO teams VALUES ('RV','Rockville','A',2013);
INSERT INTO teams VALUES ('SB','Stonebridge','G',2013);
INSERT INTO teams VALUES ('SG','Stonegate','A',2013);
INSERT INTO teams VALUES ('SL','Seven Locks','I',2013);
INSERT INTO teams VALUES ('SO','Somerset','L',2013);
INSERT INTO teams VALUES ('TA','Tanterra','I',2013);
INSERT INTO teams VALUES ('TB','Twinbrook','N',2013);
INSERT INTO teams VALUES ('TF','Twin Farms','M',2013);
INSERT INTO teams VALUES ('TH','Tallyho','C',2013);
INSERT INTO teams VALUES ('TN','Tanglewood','O',2013);
INSERT INTO teams VALUES ('TW','Tilden Woods','A',2013);
INSERT INTO teams VALUES ('UC','Upper County','A',2013);
INSERT INTO teams VALUES ('W','Whetstone','J',2013);
INSERT INTO teams VALUES ('WCF','Woodcliffe','B',2013);
INSERT INTO teams VALUES ('WG','Woodley Gardens','B',2013);
INSERT INTO teams VALUES ('WHI','West Hillandale','N',2013);
INSERT INTO teams VALUES ('WL','Westleigh','C',2013);
INSERT INTO teams VALUES ('WLP','Willows of Potomac','M',2013);
INSERT INTO teams VALUES ('WM','Wildwood Manor','E',2013);
INSERT INTO teams VALUES ('WTL','Waters Landing','I',2013);
INSERT INTO teams VALUES ('WW','Wheaton Woods','N',2013);
INSERT INTO teams VALUES ('WWD','Washingtonian Woods','O',2013);
INSERT INTO teams VALUES ('CLK','Clarksburg Village','O',2013);
