insert into teams values ('RV','Rockville','A');
insert into teams values ('TW','Tilden Woods','A');
insert into teams values ('MCT','Mill Creek Towne','A');
insert into teams values ('BE','Bethesda','A');
insert into teams values ('UC','Upper County','A');
insert into teams values ('FV','Flower Valley','A');
insert into teams values ('HA','Hallowell','B');
insert into teams values ('MCF','Manchester Farm','B');
insert into teams values ('WL','Westleigh','B');
insert into teams values ('PL','Poolesville','B');
insert into teams values ('QO','Quince Orchard','B');
insert into teams values ('SG','Stonegate','B');
insert into teams values ('OM','Olney Mill','C');
insert into teams values ('WG','Woodley Gardens','C');
insert into teams values ('DA','Damascus','C');
insert into teams values ('SB','Stonebridge','C');
insert into teams values ('C','Cedarbrook','C');
insert into teams values ('GER','Germantown','C');
insert into teams values ('SL','Seven Locks','D');
insert into teams values ('DT','Darnestown','D');
insert into teams values ('KL','Kentlands','D');
insert into teams values ('PO','Potomac','D');
insert into teams values ('PGL','Potomac Glen','D');
insert into teams values ('CG','Country Glen','D');
insert into teams values ('FR','Franklin Knolls','E');
insert into teams values ('RF','River Falls','E');
insert into teams values ('B','Bannockburn','E');
insert into teams values ('PW','Potomac Woods','E');
insert into teams values ('NWB','Northwest Branch','E');
insert into teams values ('TA','Tanterra','E');
insert into teams values ('RC','Rock Creek','F');
insert into teams values ('MM','Merrimack Park','F');
insert into teams values ('NH','Norbeck Hills','F');
insert into teams values ('LM','Lake Marion','F');
insert into teams values ('G','Glenwood','F');
insert into teams values ('RE','Regency Estates','F');
insert into teams values ('RH','Robin Hood','G');
insert into teams values ('RS','Rockshire','G');
insert into teams values ('PA','Palisades','G');
insert into teams values ('OG','Old Georgetown','G');
insert into teams values ('WTL','Waters Landing','G');
insert into teams values ('TH','Tallyho','G');
insert into teams values ('LF','Little Falls','H');
insert into teams values ('CA','Calverton','H');
insert into teams values ('GP','Garrett Park','H');
insert into teams values ('CCR','Chevy Chase Rec. Assoc.','H');
insert into teams values ('MO','Mohican','H');
insert into teams values ('IF','Inverness Forest','H');
insert into teams values ('EW','Eldwick','I');
insert into teams values ('D','Daleview','I');
insert into teams values ('SO','Somerset','I');
insert into teams values ('NCC','North Chevy Chase','I');
insert into teams values ('WCF','Woodcliffe','I');
insert into teams values ('WM','Wildwood Manor','I');
insert into teams values ('GM','Glenmont','J');
insert into teams values ('CB','Connecticut Belair','J');
insert into teams values ('CS','Carderock Springs','J');
insert into teams values ('MW','Manor Woods','J');
insert into teams values ('W','Whetstone','J');
insert into teams values ('KFM','King Farm','J');
insert into teams values ('NGV','Norbeck Grove','K');
insert into teams values ('LLD','Lakelands','K');
insert into teams values ('CLM','Clopper''s Mill','K');
insert into teams values ('A','Ashton','K');
insert into teams values ('PLT','Plantations','K');
insert into teams values ('K','Kenmont','K');
insert into teams values ('WW','Wheaton Woods','L');
insert into teams values ('OF','Old Farm','L');
insert into teams values ('FO','Forest Knolls','L');
insert into teams values ('NO','North Creek','L');
insert into teams values ('MS','Montgomery Square','L');
insert into teams values ('QV','Quail Valley','L');
insert into teams values ('FM','Fallsmead','M');
insert into teams values ('LB','Long Branch','M');
insert into teams values ('H','Hillandale','M');
insert into teams values ('EG','East Gate','M');
insert into teams values ('KM','Kemp Mill','M');
insert into teams values ('WWD','Washingtonian Woods','M');
insert into teams values ('TF','Twin Farms','N');
insert into teams values ('DF','Diamond Farm','N');
insert into teams values ('MB','Middlebridge','N');
insert into teams values ('FH','Flower Hill','N');
insert into teams values ('JC','James Creek','N');
insert into teams values ('TB','Twinbrook','N');
insert into teams values ('TN','Tanglewood','O');
insert into teams values ('NMC','New Mark Commons','O');
insert into teams values ('WHI','West Hillandale','O');
insert into teams values ('P','Parkland','O');
insert into teams values ('O','Oakview','O');
