DELETE FROM teams where year=2012;
INSERT INTO teams VALUES ('RV','Rockville','A',2012);
INSERT INTO teams VALUES ('TW','Tilden Woods','A',2012);
INSERT INTO teams VALUES ('MCT','Mill Creek Towne','B',2012);
INSERT INTO teams VALUES ('BE','Bethesda','A',2012);
INSERT INTO teams VALUES ('UC','Upper County','A',2012);
INSERT INTO teams VALUES ('FV','Flower Valley','C',2012);
INSERT INTO teams VALUES ('HA','Hallowell','D',2012);
INSERT INTO teams VALUES ('MCF','Manchester Farm','B',2012);
INSERT INTO teams VALUES ('WL','Westleigh','A',2012);
INSERT INTO teams VALUES ('PL','Poolesville','J',2012);
INSERT INTO teams VALUES ('QO','Quince Orchard','D',2012);
INSERT INTO teams VALUES ('SG','Stonegate','A',2012);
INSERT INTO teams VALUES ('OM','Olney Mill','H',2012);
INSERT INTO teams VALUES ('WG','Woodley Gardens','B',2012);
INSERT INTO teams VALUES ('DA','Damascus','F',2012);
INSERT INTO teams VALUES ('SB','Stonebridge','G',2012);
INSERT INTO teams VALUES ('C','Cedarbrook','C',2012);
INSERT INTO teams VALUES ('GER','Germantown','E',2012);
INSERT INTO teams VALUES ('SL','Seven Locks','I',2012);
INSERT INTO teams VALUES ('DT','Darnestown','B',2012);
INSERT INTO teams VALUES ('KL','Kentlands','D',2012);
INSERT INTO teams VALUES ('PO','Potomac','C',2012);
INSERT INTO teams VALUES ('PGL','Potomac Glen','B',2012);
INSERT INTO teams VALUES ('CG','Country Glen','D',2012);
INSERT INTO teams VALUES ('FR','Franklin Knolls','G',2012);
INSERT INTO teams VALUES ('RF','River Falls','C',2012);
INSERT INTO teams VALUES ('B','Bannockburn','G',2012);
INSERT INTO teams VALUES ('PW','Potomac Woods','C',2012);
INSERT INTO teams VALUES ('NWB','Northwest Branch','G',2012);
INSERT INTO teams VALUES ('TA','Tanterra','H',2012);
INSERT INTO teams VALUES ('RC','Rock Creek','I',2012);
INSERT INTO teams VALUES ('MM','Merrimack Park','E',2012);
INSERT INTO teams VALUES ('NH','Norbeck Hills','L',2012);
INSERT INTO teams VALUES ('LM','Lake Marion','H',2012);
INSERT INTO teams VALUES ('G','Glenwood','F',2012);
INSERT INTO teams VALUES ('RE','Regency Estates','D',2012);
INSERT INTO teams VALUES ('RH','Robin Hood','E',2012);
INSERT INTO teams VALUES ('RS','Rockshire','I',2012);
INSERT INTO teams VALUES ('PA','Palisades','F',2012);
INSERT INTO teams VALUES ('OG','Old Georgetown','B',2012);
INSERT INTO teams VALUES ('WTL','Waters Landing','K',2012);
INSERT INTO teams VALUES ('TH','Tallyho','C',2012);
INSERT INTO teams VALUES ('LF','Little Falls','F',2012);
INSERT INTO teams VALUES ('CA','Calverton','I',2012);
INSERT INTO teams VALUES ('GP','Garrett Park','E',2012);
INSERT INTO teams VALUES ('CCR','Chevy Chase Rec. Assoc.','E',2012);
INSERT INTO teams VALUES ('MO','Mohican','G',2012);
INSERT INTO teams VALUES ('IF','Inverness Forest','H',2012);
INSERT INTO teams VALUES ('EW','Eldwick','J',2012);
INSERT INTO teams VALUES ('D','Daleview','H',2012);
INSERT INTO teams VALUES ('SO','Somerset','L',2012);
INSERT INTO teams VALUES ('NCC','North Chevy Chase','I',2012);
INSERT INTO teams VALUES ('WCF','Woodcliffe','E',2012);
INSERT INTO teams VALUES ('WM','Wildwood Manor','G',2012);
INSERT INTO teams VALUES ('GM','Glenmont','M',2012);
INSERT INTO teams VALUES ('CB','Connecticut Belair','D',2012);
INSERT INTO teams VALUES ('CS','Carderock Springs','J',2012);
INSERT INTO teams VALUES ('MW','Manor Woods','K',2012);
INSERT INTO teams VALUES ('W','Whetstone','I',2012);
INSERT INTO teams VALUES ('KFM','King Farm','F',2012);
INSERT INTO teams VALUES ('NGV','Norbeck Grove','K',2012);
INSERT INTO teams VALUES ('LLD','Lakelands','F',2012);
INSERT INTO teams VALUES ('CLM','Clopper''s Mill','J',2012);
INSERT INTO teams VALUES ('A','Ashton','H',2012);
INSERT INTO teams VALUES ('PLT','Plantations','J',2012);
INSERT INTO teams VALUES ('K','Kenmont','K',2012);
INSERT INTO teams VALUES ('WW','Wheaton Woods','N',2012);
INSERT INTO teams VALUES ('OF','Old Farm','J',2012);
INSERT INTO teams VALUES ('FO','Forest Knolls','L',2012);
INSERT INTO teams VALUES ('NO','North Creek','L',2012);
INSERT INTO teams VALUES ('MS','Montgomery Square','L',2012);
INSERT INTO teams VALUES ('QV','Quail Valley','K',2012);
INSERT INTO teams VALUES ('FM','Fallsmead','M',2012);
INSERT INTO teams VALUES ('LB','Long Branch','L',2012);
INSERT INTO teams VALUES ('H','Hillandale','K',2012);
INSERT INTO teams VALUES ('EG','East Gate','M',2012);
INSERT INTO teams VALUES ('KM','Kemp Mill','N',2012);
INSERT INTO teams VALUES ('WWD','Washingtonian Woods','O',2012);
INSERT INTO teams VALUES ('TF','Twin Farms','M',2012);
INSERT INTO teams VALUES ('DF','Diamond Farm','M',2012);
INSERT INTO teams VALUES ('MB','Middlebridge','O',2012);
INSERT INTO teams VALUES ('FH','Flower Hill','N',2012);
INSERT INTO teams VALUES ('JC','James Creek','M',2012);
INSERT INTO teams VALUES ('TB','Twinbrook','N',2012);
INSERT INTO teams VALUES ('TN','Tanglewood','O',2012);
INSERT INTO teams VALUES ('NMC','New Mark Commons','N',2012);
INSERT INTO teams VALUES ('WHI','West Hillandale','N',2012);
INSERT INTO teams VALUES ('P','Parkland','O',2012);
INSERT INTO teams VALUES ('O','Oakview','O',2012);
INSERT INTO teams VALUES ('WLP','Willows of Potomac','O',2012);
